version: '3.8'

services:
  client:
    image: node:20.0.0-alpine
    user: node
    entrypoint: sh -c
    working_dir: /home/node
    command: '"npm install && npm run dev"'
    ports:
      - '5173:5173'
    volumes:
      - ./client:/home/node
    env_file:
      - ./client/.env

  server:
    image: node:20.0.0-alpine
    user: node
    working_dir: /home/node
    command: sh -c "npm install && npm run start"
    ports:
      - '8000:8000'
    volumes:
      - ./server:/home/node
    depends_on:
      - postgres
      - mongo
    env_file:
      - ./server/.env

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./postgres/.env

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    env_file:
      - ./mongo/.env

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    env_file:
      - ./mongo/.env

volumes:
  postgres-data:
  mongo-data:
