name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - uses: actions/checkout@v2

    - name: Create .env files if they do not exist
      run: |
        mkdir -p mongo postgres client nginx
        if [ ! -f mongo/.env ]; then echo "MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=secret" > mongo/.env; fi
        if [ ! -f postgres/.env ]; then echo "POSTGRES_USER=admin\nPOSTGRES_PASSWORD=secret" > postgres/.env; fi
        if [ ! -f client/.env ]; then echo "REACT_APP_API_URL=http://localhost:8000" > client/.env; fi
        if [ ! -f nginx/.env ]; then echo "NGINX_HOST=localhost\nNGINX_PORT=80" > nginx/.env; fi


    - name: Build Docker containers
      run: sudo docker-compose -f docker-compose.prod.yml build

    - name: Run tests
      run: sudo docker-compose -f docker-compose.prod.yml up -d && sudo docker-compose -f docker-compose.prod.yml exec server npm run test

    - name: Stop Docker containers
      run: sudo docker-compose -f docker-compose.prod.yml down
.
